
#include <clang/Rewrite/Core/Rewriter.h>
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/Stmt.h"
#include "clang/Basic/SourceManager.h"

//-----------------------------------------------------------------------------
// RecursiveASTVisitor
//-----------------------------------------------------------------------------
class CodeStyleCheckerVisitor
        : public clang::RecursiveASTVisitor<CodeStyleCheckerVisitor> {
public:
    //Rewriter:4:  Consumer将Rewriter传递给Visitor
    explicit CodeStyleCheckerVisitor(clang::Rewriter &R, clang::ASTContext *Ctx)
    //Rewriter:5:  Consumer将Rewriter传递给Visitor, 并由Visitor.mRewriter接收
    : mRewriter(R),
    Ctx(Ctx)
    {

    }

    static void insertIncludeToMainFile(clang::ASTContext &Context, clang::Rewriter& rewriter);
    static bool getSourceFilePathAtLoc(clang::SourceLocation Loc, const clang::SourceManager &SM,clang::StringRef& fn);
    static bool getSourceFilePathOfStmt(const clang::Stmt *S, const clang::SourceManager &SM,clang::StringRef& fn);
    /**遍历语句
     *
     * @param S
     * @return
     */
    virtual bool VisitStmt(clang::Stmt *S);
    virtual bool VisitCallExpr(clang::CallExpr *callExpr);

    //下面4个形如 bool VisitZzz(clang:Zzz *Decl)  的方法:, 其中Zzz的完整列表叙述 从 本文件第27行开始.
    bool VisitCXXRecordDecl(clang::CXXRecordDecl *Decl);
    bool VisitFunctionDecl(clang::FunctionDecl *Decl);
    bool VisitVarDecl(clang::VarDecl *Decl);
    bool VisitFieldDecl(clang::FieldDecl *Decl);
/*  类 RecursiveASTVisitor 中 有大量 形如 bool VisitZzz(clang:Zzz *Decl) 的方法, 其中Zzz即是可以被Visit的语法节点, Zzz列表完整如下:
grep DEF_TRAVERSE_STMT   '/llvm_release_home/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4/include/clang/AST/RecursiveASTVisitor.h'
DEF_TRAVERSE_STMT(GCCAsmStmt
DEF_TRAVERSE_STMT(CXXCatchStmt
DEF_TRAVERSE_STMT(DeclStmt
DEF_TRAVERSE_STMT(BreakStmt
DEF_TRAVERSE_STMT(CXXTryStmt
DEF_TRAVERSE_STMT(CaseStmt
DEF_TRAVERSE_STMT(CompoundStmt
DEF_TRAVERSE_STMT(ContinueStmt
DEF_TRAVERSE_STMT(DefaultStmt
DEF_TRAVERSE_STMT(DoStmt
DEF_TRAVERSE_STMT(ForStmt
DEF_TRAVERSE_STMT(GotoStmt
DEF_TRAVERSE_STMT(IfStmt
DEF_TRAVERSE_STMT(IndirectGotoStmt
DEF_TRAVERSE_STMT(LabelStmt
DEF_TRAVERSE_STMT(AttributedStmt
DEF_TRAVERSE_STMT(NullStmt
DEF_TRAVERSE_STMT(ObjCAtCatchStmt
DEF_TRAVERSE_STMT(ObjCAtFinallyStmt
DEF_TRAVERSE_STMT(ObjCAtSynchronizedStmt
DEF_TRAVERSE_STMT(ObjCAtThrowStmt
DEF_TRAVERSE_STMT(ObjCAtTryStmt
DEF_TRAVERSE_STMT(ObjCForCollectionStmt
DEF_TRAVERSE_STMT(ObjCAutoreleasePoolStmt
DEF_TRAVERSE_STMT(CXXForRangeStmt
DEF_TRAVERSE_STMT(MSDependentExistsStmt
DEF_TRAVERSE_STMT(ReturnStmt
DEF_TRAVERSE_STMT(SwitchStmt
DEF_TRAVERSE_STMT(WhileStmt
DEF_TRAVERSE_STMT(ConstantExpr
DEF_TRAVERSE_STMT(CXXDependentScopeMemberExpr
DEF_TRAVERSE_STMT(DeclRefExpr
DEF_TRAVERSE_STMT(DependentScopeDeclRefExpr
DEF_TRAVERSE_STMT(MemberExpr
DEF_TRAVERSE_STMT(CStyleCastExpr
DEF_TRAVERSE_STMT(CXXFunctionalCastExpr
DEF_TRAVERSE_STMT(CXXAddrspaceCastExpr
DEF_TRAVERSE_STMT(CXXConstCastExpr
DEF_TRAVERSE_STMT(CXXDynamicCastExpr
DEF_TRAVERSE_STMT(CXXReinterpretCastExpr
DEF_TRAVERSE_STMT(CXXStaticCastExpr
DEF_TRAVERSE_STMT(BuiltinBitCastExpr
DEF_TRAVERSE_STMT(GenericSelectionExpr
DEF_TRAVERSE_STMT(PseudoObjectExpr
DEF_TRAVERSE_STMT(CXXScalarValueInitExpr
DEF_TRAVERSE_STMT(CXXNewExpr
DEF_TRAVERSE_STMT(OffsetOfExpr
DEF_TRAVERSE_STMT(UnaryExprOrTypeTraitExpr
DEF_TRAVERSE_STMT(CXXTypeidExpr
DEF_TRAVERSE_STMT(MSPropertyRefExpr
DEF_TRAVERSE_STMT(MSPropertySubscriptExpr
DEF_TRAVERSE_STMT(CXXUuidofExpr
DEF_TRAVERSE_STMT(TypeTraitExpr
DEF_TRAVERSE_STMT(ArrayTypeTraitExpr
DEF_TRAVERSE_STMT(ExpressionTraitExpr
DEF_TRAVERSE_STMT(VAArgExpr
DEF_TRAVERSE_STMT(CXXTemporaryObjectExpr
DEF_TRAVERSE_STMT(LambdaExpr
DEF_TRAVERSE_STMT(CXXUnresolvedConstructExpr
DEF_TRAVERSE_STMT(CXXConstructExpr
DEF_TRAVERSE_STMT(CallExpr
DEF_TRAVERSE_STMT(CXXMemberCallExpr
DEF_TRAVERSE_STMT(AddrLabelExpr
DEF_TRAVERSE_STMT(ArraySubscriptExpr
DEF_TRAVERSE_STMT(MatrixSubscriptExpr
DEF_TRAVERSE_STMT(OMPArraySectionExpr
DEF_TRAVERSE_STMT(OMPArrayShapingExpr
DEF_TRAVERSE_STMT(OMPIteratorExpr
DEF_TRAVERSE_STMT(BlockExpr
DEF_TRAVERSE_STMT(ChooseExpr
DEF_TRAVERSE_STMT(CompoundLiteralExpr
DEF_TRAVERSE_STMT(CXXBindTemporaryExpr
DEF_TRAVERSE_STMT(CXXBoolLiteralExpr
DEF_TRAVERSE_STMT(CXXDefaultArgExpr
DEF_TRAVERSE_STMT(CXXDefaultInitExpr
DEF_TRAVERSE_STMT(CXXDeleteExpr
DEF_TRAVERSE_STMT(ExprWithCleanups
DEF_TRAVERSE_STMT(CXXInheritedCtorInitExpr
DEF_TRAVERSE_STMT(CXXNullPtrLiteralExpr
DEF_TRAVERSE_STMT(CXXStdInitializerListExpr
DEF_TRAVERSE_STMT(CXXPseudoDestructorExpr
DEF_TRAVERSE_STMT(CXXThisExpr
DEF_TRAVERSE_STMT(CXXThrowExpr
DEF_TRAVERSE_STMT(UserDefinedLiteral
DEF_TRAVERSE_STMT(DesignatedInitExpr
DEF_TRAVERSE_STMT(DesignatedInitUpdateExpr
DEF_TRAVERSE_STMT(ExtVectorElementExpr
DEF_TRAVERSE_STMT(GNUNullExpr
DEF_TRAVERSE_STMT(ImplicitValueInitExpr
DEF_TRAVERSE_STMT(NoInitExpr
DEF_TRAVERSE_STMT(ArrayInitLoopExpr
DEF_TRAVERSE_STMT(ArrayInitIndexExpr
DEF_TRAVERSE_STMT(ObjCBoolLiteralExpr
DEF_TRAVERSE_STMT(ObjCEncodeExpr
DEF_TRAVERSE_STMT(ObjCIsaExpr
DEF_TRAVERSE_STMT(ObjCIvarRefExpr
DEF_TRAVERSE_STMT(ObjCMessageExpr
DEF_TRAVERSE_STMT(ObjCPropertyRefExpr
DEF_TRAVERSE_STMT(ObjCSubscriptRefExpr
DEF_TRAVERSE_STMT(ObjCProtocolExpr
DEF_TRAVERSE_STMT(ObjCSelectorExpr
DEF_TRAVERSE_STMT(ObjCIndirectCopyRestoreExpr
DEF_TRAVERSE_STMT(ObjCBridgedCastExpr
DEF_TRAVERSE_STMT(ObjCAvailabilityCheckExpr
DEF_TRAVERSE_STMT(ParenExpr
DEF_TRAVERSE_STMT(ParenListExpr
DEF_TRAVERSE_STMT(SYCLUniqueStableNameExpr
DEF_TRAVERSE_STMT(PredefinedExpr
DEF_TRAVERSE_STMT(ShuffleVectorExpr
DEF_TRAVERSE_STMT(ConvertVectorExpr
DEF_TRAVERSE_STMT(StmtExpr
DEF_TRAVERSE_STMT(SourceLocExpr
DEF_TRAVERSE_STMT(UnresolvedLookupExpr
DEF_TRAVERSE_STMT(UnresolvedMemberExpr
DEF_TRAVERSE_STMT(SEHTryStmt
DEF_TRAVERSE_STMT(SEHExceptStmt
DEF_TRAVERSE_STMT(SEHFinallyStmt
DEF_TRAVERSE_STMT(SEHLeaveStmt
DEF_TRAVERSE_STMT(CapturedStmt
DEF_TRAVERSE_STMT(CXXOperatorCallExpr
DEF_TRAVERSE_STMT(CXXRewrittenBinaryOperator
DEF_TRAVERSE_STMT(OpaqueValueExpr
DEF_TRAVERSE_STMT(TypoExpr
DEF_TRAVERSE_STMT(RecoveryExpr
DEF_TRAVERSE_STMT(CUDAKernelCallExpr
DEF_TRAVERSE_STMT(BinaryConditionalOperator
DEF_TRAVERSE_STMT(ConditionalOperator
DEF_TRAVERSE_STMT(UnaryOperator
DEF_TRAVERSE_STMT(BinaryOperator
DEF_TRAVERSE_STMT(CompoundAssignOperator
DEF_TRAVERSE_STMT(CXXNoexceptExpr
DEF_TRAVERSE_STMT(PackExpansionExpr
DEF_TRAVERSE_STMT(SizeOfPackExpr
DEF_TRAVERSE_STMT(SubstNonTypeTemplateParmPackExpr
DEF_TRAVERSE_STMT(SubstNonTypeTemplateParmExpr
DEF_TRAVERSE_STMT(FunctionParmPackExpr
DEF_TRAVERSE_STMT(CXXFoldExpr
DEF_TRAVERSE_STMT(AtomicExpr
DEF_TRAVERSE_STMT(MaterializeTemporaryExpr
DEF_TRAVERSE_STMT(CoroutineBodyStmt
DEF_TRAVERSE_STMT(CoreturnStmt
DEF_TRAVERSE_STMT(CoawaitExpr
DEF_TRAVERSE_STMT(DependentCoawaitExpr
DEF_TRAVERSE_STMT(CoyieldExpr
DEF_TRAVERSE_STMT(ConceptSpecializationExpr
DEF_TRAVERSE_STMT(RequiresExpr
DEF_TRAVERSE_STMT(IntegerLiteral
DEF_TRAVERSE_STMT(FixedPointLiteral
DEF_TRAVERSE_STMT(CharacterLiteral
DEF_TRAVERSE_STMT(FloatingLiteral
DEF_TRAVERSE_STMT(ImaginaryLiteral
DEF_TRAVERSE_STMT(StringLiteral
DEF_TRAVERSE_STMT(ObjCStringLiteral
DEF_TRAVERSE_STMT(ObjCBoxedExpr
DEF_TRAVERSE_STMT(ObjCArrayLiteral
DEF_TRAVERSE_STMT(ObjCDictionaryLiteral
DEF_TRAVERSE_STMT(AsTypeExpr
DEF_TRAVERSE_STMT(OMPCanonicalLoop
DEF_TRAVERSE_STMT(OMPMetaDirective
DEF_TRAVERSE_STMT(OMPParallelDirective
DEF_TRAVERSE_STMT(OMPSimdDirective
DEF_TRAVERSE_STMT(OMPTileDirective
DEF_TRAVERSE_STMT(OMPUnrollDirective
DEF_TRAVERSE_STMT(OMPForDirective
DEF_TRAVERSE_STMT(OMPForSimdDirective
DEF_TRAVERSE_STMT(OMPSectionsDirective
DEF_TRAVERSE_STMT(OMPSectionDirective
DEF_TRAVERSE_STMT(OMPSingleDirective
DEF_TRAVERSE_STMT(OMPMasterDirective
DEF_TRAVERSE_STMT(OMPCriticalDirective
DEF_TRAVERSE_STMT(OMPParallelForDirective
DEF_TRAVERSE_STMT(OMPParallelForSimdDirective
DEF_TRAVERSE_STMT(OMPParallelMasterDirective
DEF_TRAVERSE_STMT(OMPParallelMaskedDirective
DEF_TRAVERSE_STMT(OMPParallelSectionsDirective
DEF_TRAVERSE_STMT(OMPTaskDirective
DEF_TRAVERSE_STMT(OMPTaskyieldDirective
DEF_TRAVERSE_STMT(OMPBarrierDirective
DEF_TRAVERSE_STMT(OMPTaskwaitDirective
DEF_TRAVERSE_STMT(OMPTaskgroupDirective
DEF_TRAVERSE_STMT(OMPCancellationPointDirective
DEF_TRAVERSE_STMT(OMPCancelDirective
DEF_TRAVERSE_STMT(OMPFlushDirective
DEF_TRAVERSE_STMT(OMPDepobjDirective
DEF_TRAVERSE_STMT(OMPScanDirective
DEF_TRAVERSE_STMT(OMPOrderedDirective
DEF_TRAVERSE_STMT(OMPAtomicDirective
DEF_TRAVERSE_STMT(OMPTargetDirective
DEF_TRAVERSE_STMT(OMPTargetDataDirective
DEF_TRAVERSE_STMT(OMPTargetEnterDataDirective
DEF_TRAVERSE_STMT(OMPTargetExitDataDirective
DEF_TRAVERSE_STMT(OMPTargetParallelDirective
DEF_TRAVERSE_STMT(OMPTargetParallelForDirective
DEF_TRAVERSE_STMT(OMPTeamsDirective
DEF_TRAVERSE_STMT(OMPTargetUpdateDirective
DEF_TRAVERSE_STMT(OMPTaskLoopDirective
DEF_TRAVERSE_STMT(OMPTaskLoopSimdDirective
DEF_TRAVERSE_STMT(OMPMasterTaskLoopDirective
DEF_TRAVERSE_STMT(OMPMasterTaskLoopSimdDirective
DEF_TRAVERSE_STMT(OMPParallelMasterTaskLoopDirective
DEF_TRAVERSE_STMT(OMPParallelMasterTaskLoopSimdDirective
DEF_TRAVERSE_STMT(OMPMaskedTaskLoopDirective
DEF_TRAVERSE_STMT(OMPMaskedTaskLoopSimdDirective
DEF_TRAVERSE_STMT(OMPParallelMaskedTaskLoopDirective
DEF_TRAVERSE_STMT(OMPParallelMaskedTaskLoopSimdDirective
DEF_TRAVERSE_STMT(OMPDistributeDirective
DEF_TRAVERSE_STMT(OMPDistributeParallelForDirective
DEF_TRAVERSE_STMT(OMPDistributeParallelForSimdDirective
DEF_TRAVERSE_STMT(OMPDistributeSimdDirective
DEF_TRAVERSE_STMT(OMPTargetParallelForSimdDirective
DEF_TRAVERSE_STMT(OMPTargetSimdDirective
DEF_TRAVERSE_STMT(OMPTeamsDistributeDirective
DEF_TRAVERSE_STMT(OMPTeamsDistributeSimdDirective
DEF_TRAVERSE_STMT(OMPTeamsDistributeParallelForSimdDirective
DEF_TRAVERSE_STMT(OMPTeamsDistributeParallelForDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsDistributeDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsDistributeParallelForDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsDistributeParallelForSimdDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsDistributeSimdDirective
DEF_TRAVERSE_STMT(OMPInteropDirective
DEF_TRAVERSE_STMT(OMPDispatchDirective
DEF_TRAVERSE_STMT(OMPMaskedDirective
DEF_TRAVERSE_STMT(OMPGenericLoopDirective
DEF_TRAVERSE_STMT(OMPTeamsGenericLoopDirective
DEF_TRAVERSE_STMT(OMPTargetTeamsGenericLoopDirective
DEF_TRAVERSE_STMT(OMPParallelGenericLoopDirective
DEF_TRAVERSE_STMT(OMPTargetParallelGenericLoopDirective

grep DEF_TRAVERSE_DECL   '/llvm_release_home/clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4/include/clang/AST/RecursiveASTVisitor.h'
DEF_TRAVERSE_DECL(AccessSpecDecl
DEF_TRAVERSE_DECL(BlockDecl
DEF_TRAVERSE_DECL(CapturedDecl
DEF_TRAVERSE_DECL(EmptyDecl
DEF_TRAVERSE_DECL(LifetimeExtendedTemporaryDecl
DEF_TRAVERSE_DECL(FileScopeAsmDecl
DEF_TRAVERSE_DECL(ImportDecl
DEF_TRAVERSE_DECL(FriendDecl
DEF_TRAVERSE_DECL(FriendTemplateDecl
DEF_TRAVERSE_DECL(ClassScopeFunctionSpecializationDecl
DEF_TRAVERSE_DECL(LinkageSpecDecl
DEF_TRAVERSE_DECL(ExportDecl
DEF_TRAVERSE_DECL(ObjCPropertyImplDecl
DEF_TRAVERSE_DECL(StaticAssertDecl
DEF_TRAVERSE_DECL(TranslationUnitDecl
DEF_TRAVERSE_DECL(PragmaCommentDecl
DEF_TRAVERSE_DECL(PragmaDetectMismatchDecl
DEF_TRAVERSE_DECL(ExternCContextDecl
DEF_TRAVERSE_DECL(NamespaceAliasDecl
DEF_TRAVERSE_DECL(LabelDecl
DEF_TRAVERSE_DECL(ObjCCompatibleAliasDecl
DEF_TRAVERSE_DECL(ObjCCategoryDecl
DEF_TRAVERSE_DECL(ObjCCategoryImplDecl
DEF_TRAVERSE_DECL(ObjCImplementationDecl
DEF_TRAVERSE_DECL(ObjCInterfaceDecl
DEF_TRAVERSE_DECL(ObjCProtocolDecl
DEF_TRAVERSE_DECL(ObjCMethodDecl
DEF_TRAVERSE_DECL(ObjCTypeParamDecl
DEF_TRAVERSE_DECL(ObjCPropertyDecl
DEF_TRAVERSE_DECL(UsingDecl
DEF_TRAVERSE_DECL(UsingEnumDecl
DEF_TRAVERSE_DECL(UsingPackDecl
DEF_TRAVERSE_DECL(UsingDirectiveDecl
DEF_TRAVERSE_DECL(UsingShadowDecl
DEF_TRAVERSE_DECL(ConstructorUsingShadowDecl
DEF_TRAVERSE_DECL(OMPThreadPrivateDecl
DEF_TRAVERSE_DECL(OMPRequiresDecl
DEF_TRAVERSE_DECL(OMPDeclareReductionDecl
DEF_TRAVERSE_DECL(OMPDeclareMapperDecl
DEF_TRAVERSE_DECL(OMPCapturedExprDecl
DEF_TRAVERSE_DECL(OMPAllocateDecl
DEF_TRAVERSE_DECL(TemplateTemplateParmDecl
DEF_TRAVERSE_DECL(BuiltinTemplateDecl
DEF_TRAVERSE_DECL(TemplateTypeParmDecl
DEF_TRAVERSE_DECL(TypedefDecl
DEF_TRAVERSE_DECL(TypeAliasDecl
DEF_TRAVERSE_DECL(TypeAliasTemplateDecl
DEF_TRAVERSE_DECL(ConceptDecl
DEF_TRAVERSE_DECL(UnresolvedUsingTypenameDecl
DEF_TRAVERSE_DECL(UnresolvedUsingIfExistsDecl
DEF_TRAVERSE_DECL(EnumDecl
DEF_TRAVERSE_DECL(RecordDecl
DEF_TRAVERSE_DECL(CXXRecordDecl
DEF_TRAVERSE_DECL(EnumConstantDecl
DEF_TRAVERSE_DECL(UnresolvedUsingValueDecl
DEF_TRAVERSE_DECL(IndirectFieldDecl
DEF_TRAVERSE_DECL(DecompositionDecl
DEF_TRAVERSE_DECL(BindingDecl
DEF_TRAVERSE_DECL(MSPropertyDecl
DEF_TRAVERSE_DECL(MSGuidDecl
DEF_TRAVERSE_DECL(UnnamedGlobalConstantDecl
DEF_TRAVERSE_DECL(TemplateParamObjectDecl
DEF_TRAVERSE_DECL(FieldDecl
DEF_TRAVERSE_DECL(ObjCAtDefsFieldDecl
DEF_TRAVERSE_DECL(ObjCIvarDecl
DEF_TRAVERSE_DECL(FunctionDecl
DEF_TRAVERSE_DECL(CXXDeductionGuideDecl
DEF_TRAVERSE_DECL(CXXMethodDecl
DEF_TRAVERSE_DECL(CXXConstructorDecl
DEF_TRAVERSE_DECL(CXXConversionDecl
DEF_TRAVERSE_DECL(CXXDestructorDecl
DEF_TRAVERSE_DECL(VarDecl
DEF_TRAVERSE_DECL(ImplicitParamDecl
DEF_TRAVERSE_DECL(NonTypeTemplateParmDecl
DEF_TRAVERSE_DECL(ParmVarDecl
DEF_TRAVERSE_DECL(RequiresExprBodyDecl
 */

public:
    clang::Rewriter mRewriter;

private:
    clang::ASTContext *Ctx;

};
